// src/components/TypstEditor.tsx
'use client'

import { useState, useEffect, useRef } from 'react'
import { TypstCompilerService, type CompileStatus } from '@/lib/typst/TypstCompilerService'
import { debounce, downloadPdfFromUrl } from '@/lib/utils/helpers'

export default function TypstEditor() {
	const [typstCode, setTypstCode] = useState(`= Hello Typst

This is a test.`)
	const [status, setStatus] = useState<CompileStatus>('idle')
	const [pdfUrl, setPdfUrl] = useState<string | null>(null)
	const [errorMsg, setErrorMsg] = useState<string | null>(null)

	const compilerServiceRef = useRef<TypstCompilerService | null>(null)
	const debouncedCompileRef = useRef<ReturnType<typeof debounce> | null>(null)

	useEffect(() => {
		// Initialize compiler service
		const compilerService = new TypstCompilerService()
		compilerServiceRef.current = compilerService

		// Listen to compile events
		const unsubscribe = compilerService.addListener({
			onStatusChange: (newStatus) => {
				setStatus(newStatus)
			},
			onSuccess: (pdf, url) => {
				setPdfUrl(url)
				setErrorMsg(null)
			},
			onError: (error) => {
				setErrorMsg(error)
				setPdfUrl(null)
			},
		})

		// Create debounced compile function
		debouncedCompileRef.current = debounce(async (code: string) => {
			if (compilerServiceRef.current) {
				await compilerServiceRef.current.compile(code)
			}
		}, 1000)

		return () => {
			debouncedCompileRef.current?.cancel()
			unsubscribe()
			compilerService.dispose()
		}
	}, [])

	// Watch for code changes and trigger debounced compile
	useEffect(() => {
		if (debouncedCompileRef.current && compilerServiceRef.current) {
			debouncedCompileRef.current(typstCode)
		}
	}, [typstCode])

	async function handleCompileNow() {
		if (compilerServiceRef.current) {
			await compilerServiceRef.current.compile(typstCode)
		}
	}

	function handleDownload() {
		if (pdfUrl) {
			downloadPdfFromUrl(pdfUrl, 'document.pdf')
		}
	}

	return (
		<div className="flex flex-col h-screen bg-gray-900 text-white">
			<div className="flex justify-between items-center px-4 py-3 bg-gray-800 border-b border-gray-700">
				<h1 className="text-xl font-semibold">Typst Online Editor</h1>
				<div className="flex items-center gap-4">
					<div className="text-sm">
						{status === 'compiling' && '⏳ Compiling...'}
						{status === 'done' && '✅ Ready'}
						{status === 'error' && '❌ Error'}
						{status === 'idle' && 'Ready'}
					</div>
					<button
						className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 disabled:opacity-50 disabled:cursor-not-allowed"
						onClick={handleCompileNow}
						disabled={status === 'compiling'}
					>
						Compile Now
					</button>
					{pdfUrl && (
						<button
							className="px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700"
							onClick={handleDownload}
						>
							Download PDF
						</button>
					)}
				</div>
			</div>

			<div className="flex flex-1 overflow-hidden">
				<div className="flex-1 flex flex-col border-r border-gray-700">
					<textarea
						className="flex-1 bg-gray-900 text-white p-4 font-mono text-sm resize-none focus:outline-none"
						value={typstCode}
						onChange={(e) => setTypstCode(e.target.value)}
						placeholder="Type Typst code here..."
					/>
				</div>

				<div className="flex-1 flex items-center justify-center bg-gray-800">
					{pdfUrl ? (
						<iframe
							src={pdfUrl}
							title="PDF Preview"
							className="w-full h-full border-0"
						/>
					) : (
						<div className="text-center text-gray-400">
							{status === 'compiling' && <p className="text-lg">⏳ Compiling...</p>}
							{status === 'error' && (
								<>
									<p className="text-lg text-red-500">❌ Error</p>
									<pre className="mt-2 text-sm text-left max-w-2xl overflow-auto p-4 bg-gray-900 rounded">
										{errorMsg}
									</pre>
								</>
							)}
							{status === 'idle' && (
								<p className="text-lg">Click "Compile Now" to generate PDF</p>
							)}
							<p className="mt-4 text-sm">Code: {typstCode.length} chars</p>
						</div>
					)}
				</div>
			</div>
		</div>
	)
}

// src/components/TypstEditor.svelte
<script lang="ts">

  // SVELTE EDITOR UI (FOR INSPIRATION ONLY)

  import { onMount } from 'svelte'
  import { TypstCompilerService, type CompileStatus } from '$lib/typst/TypstCompilerService'
  import { debounce, downloadPdfFromUrl } from '$lib/utils/helpers'
  
  let typstCode = $state(`= Hello Typst

This is a test.`)
  let status = $state<CompileStatus>('idle')
  let pdfUrl = $state<string | null>(null)
  let errorMsg = $state<string | null>(null)
  
  let compilerService: TypstCompilerService | null = null
  let debouncedCompile: ReturnType<typeof debounce> | null = null
  
  // Watch for code changes and trigger debounced compile
  $effect(() => {
    const code = typstCode
    if (debouncedCompile && compilerService) {
      debouncedCompile(code)
    }
  })
  
  onMount(() => {
    // Initialize compiler service
    compilerService = new TypstCompilerService()
    
    // Listen to compile events
    const unsubscribe = compilerService.addListener({
      onStatusChange: (newStatus) => {
        status = newStatus
      },
      onSuccess: (pdf, url) => {
        pdfUrl = url
        errorMsg = null
      },
      onError: (error) => {
        errorMsg = error
        pdfUrl = null
      },
    })
    
    // Create debounced compile function
    debouncedCompile = debounce(async (code: string) => {
      if (compilerService) {
        await compilerService.compile(code)
      }
    }, 1000)
    
    return () => {
      debouncedCompile?.cancel()
      unsubscribe()
      compilerService?.dispose()
    }
  })
  
  async function handleCompileNow() {
    if (compilerService) {
      await compilerService.compile(typstCode)
    }
  }
  
  function handleDownload() {
    if (pdfUrl) {
      downloadPdfFromUrl(pdfUrl, 'document.pdf')
    }
  }
</script>

<div class="editor-container">
  <div class="navbar">
    <h1 class="title">Typst Online Editor</h1>
    <div class="status">
      {#if status === 'compiling'}⏳ Compiling...
      {:else if status === 'done'}✅ Ready
      {:else if status === 'error'}❌ Error
      {:else}Ready{/if}
    </div>
    <button class="btn" onclick={handleCompileNow} disabled={status === 'compiling'}>
      Compile Now
    </button>
    {#if pdfUrl}
      <button class="btn" onclick={handleDownload}>Download PDF</button>
    {/if}
  </div>
  
  <div class="content">
    <div class="editor-pane">
      <textarea 
        bind:value={typstCode}
        placeholder="Type Typst code here..."
      ></textarea>
    </div>
    
    <div class="preview-pane">
      {#if pdfUrl}
        <iframe src={pdfUrl} title="PDF Preview" class="pdf-iframe"></iframe>
      {:else}
        <div class="preview-placeholder">
          {#if status === 'compiling'}
            <p>⏳ Compiling...</p>
          {:else if status === 'error'}
            <p style="color: #f44336">❌ Error</p>
            <pre>{errorMsg}</pre>
          {:else}
            <p>Click "Compile Now" to generate PDF</p>
          {/if}
          <p style="margin-top: 1rem; font-size: 0.875rem;">Code: {typstCode.length} chars</p>
        </div>
      {/if}
    </div>
  </div>
</div>

<style>
  .editor-container {
    display: flex;
    flex-direction: column;
    height: 100vh;
    background: #1e1e1e;
    color: #fff;
  }

  .navbar {
    display: flex;
    justify-content: space-between;
    align-items: center;
    padding: 1rem;
    background: #252525;
    border-bottom: 1px solid #333;
  }

  .title {
    margin: 0;
    font-size: 1.25rem;
  }

  .btn {
    padding: 0.5rem 1rem;
    background: #0066cc;
    color: white;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  .btn:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }

  .content {
    display: flex;
    flex: 1;
    overflow: hidden;
  }

  .editor-pane {
    flex: 1;
    display: flex;
    flex-direction: column;
    border-right: 1px solid #333;
  }

  textarea {
    flex: 1;
    background: #1e1e1e;
    color: #fff;
    border: none;
    padding: 1rem;
    font-family: monospace;
    font-size: 14px;
    resize: none;
  }

  .preview-pane {
    flex: 1;
    display: flex;
    align-items: center;
    justify-content: center;
    background: #2a2a2a;
    position: relative;
  }

  .pdf-iframe {
    width: 100%;
    height: 100%;
    border: none;
  }

  .preview-placeholder {
    text-align: center;
    color: #888;
  }
</style>
